name: Application CI
on: [push, pull_request]
jobs:
    validation:
        name: "Gradle Wrapper Validation"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: gradle/wrapper-validation-action@v1
    pipeline:
        name: inventory pipeline
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
        timeout-minutes: 40
        env:
            NODE_VERSION: 12.16.1
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SPRING_JPA_SHOW_SQL: false
            JHI_DISABLE_WEBPACK_LOGS: true
            NG_CLI_ANALYTICS: false
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.16.1
            - uses: actions/setup-java@v1
              with:
                  java-version: '11.x'
            - name: Install node.js packages
              run: npm install
            - name: Build Docker image
              run: ./gradlew bootJar -Pprod jibDockerBuild
            - name: Docker image
              run: docker images
            - name: Launch Docker-compose app
              run: |
                docker-compose -f src/main/docker/app.yml up -d
                sleep 10
                docker ps -a
            - name: Sleep 120s
              run: sleep 120
            - name: Log Zookeeper
              run: docker logs docker_zookeeper_1
            - name: Log Kafka
              run: docker logs docker_kafka_1
            - name: Log app
              run: docker logs docker_inventory-app_1
